---
title: "Course overview"
date: today
author: "Vicki Hodgson, Matt Castle, Rob Nicholls and Martin van Rongen*"
number-sections: false
---

## Overview 

Welcome to the wonderful world of generalised linear models! These sessions teach you how to analyse non-continuous responses, such as binary (yes/no) and count data. Our primary focus is not on mathematical derivations, but on developing an intuitive understanding of the underlying statistical concepts and applying these to data. We use programming languages to help us with this and hope that, by the end of this course, you'll be confident to apply these concepts to your own research data.

::: {.callout-tip}
### Learning Objectives

To know what to do when presented with an arbitrary data set e.g.

1. Construct
    a.  a logistic model for binary response variables
    b.  a logistic model for proportion response variables
    c.  a Poisson model for count response variables
    d.  a Negative binomial model for count response variables
2. Plot the data and the fitted curve in each case for both continuous and categorical predictors
3. Assess the significance of fit
4. Assess the goodness-of-fit
5. Assess assumption of the model
:::

### Target Audience

These materials are aimed at people who have to analyse (research) data and encounter non-continuous responses. 


### Prerequisites

A solid understanding of statistics, ideally through attending our [Core statistics](https://cambiotraining.github.io/corestats/) course. Additionally, a good working ability for coding is required - either in R or Python. See our [Data analysis](https://cambiotraining.github.io/data-analysis-in-r-and-python/) courses as an example.

All current scheduled events can be found [here](https://www.training.cam.ac.uk/bioinformatics/event-timetable).

<!-- Training Developer note: comment the following section out if you did not assign levels to your exercises -->
### Exercises

Exercises in these materials are labelled according to their level of difficulty:

| Level | Description |
| ----: | :---------- |
| {{< fa solid star >}} {{< fa regular star >}} {{< fa regular star >}} | Exercises in level 1 are simpler and designed to get you familiar with the concepts and syntax covered in the course. |
| {{< fa solid star >}} {{< fa solid star >}} {{< fa regular star >}} | Exercises in level 2 combine different concepts together and apply it to a given task. |
| {{< fa solid star >}} {{< fa solid star >}} {{< fa solid star >}} | Exercises in level 3 require going beyond the concepts and syntax introduced to solve new problems. |


## Citation & Authors

Please cite these materials if:

- You adapted or used any of them in your own teaching.
- These materials were useful for your research work. For example, you can cite us in the methods section of your paper: "We carried our analyses based on the recommendations in _YourReferenceHere_".

<!-- 
This is generated automatically from the CITATION.cff file. 
If you think you should be added as an author, please get in touch with us.
-->

{{< citation CITATION.cff >}}


## Acknowledgements

<!-- if there are no acknowledgements we can delete this section -->

- We thank Hugo Tavares for constructive feedback on the manuscript.
