# essential libraries
library(broom)
library(corrr)
library(distributional)
library(downlit)
library(downloadthis)
library(ggdist)
library(ggResidpanel)
library(janitor)
library(knitr)
library(patchwork)
library(pwr)
library(reticulate)
library(rstatix)
library(tidyverse)
library(lmtest)
library(MASS)
library(performance)
library(see)

theme_set(theme_bw())

